<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Helpers\" />
    <Folder Include="Enums\" />
    <Folder Include="Services\Admin\DTOs\" />
    <Folder Include="Services\Admin\Interfaces\" />
    <Folder Include="Services\Authuser\DTOs\" />
    <Folder Include="Services\Authuser\Interfaces\" />
    <Folder Include="Services\JobProvider\DTOs\" />
    <Folder Include="Services\JobProvider\Interfaces\" />
    <Folder Include="Services\JobSeeker\DTOs\" />
    <Folder Include="Services\JobSeeker\Interfaces\" />
    <Folder Include="Services\Job\DTOs\" />
    <Folder Include="Services\Job\Interfaces\" />
    <Folder Include="Services\Chat\" />
    <Folder Include="Services\Login\DTOs\" />
    <Folder Include="Services\Login\Interfaces\" />
    <Folder Include="Services\Profile\DTOs\" />
    <Folder Include="Services\Profile\Interfaces\" />
    <Folder Include="Services\SignUp\DTOs\" />
    <Folder Include="Services\SignUp\Interfaces\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MimeKit" Version="4.16.0" />
  </ItemGroup>
</Project>