<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainJobPortal\DomainJobPortal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="API\Admin\" />
    <Folder Include="API\JobProvider\" />
    <Folder Include="API\JobSeeker\" />
    <Folder Include="API\Chat\" />
    <Folder Include="API\Job\" />
    <Folder Include="Extensions\" />
    <Folder Include="JobSeeker\" />
    <Folder Include="HubConfig\" />
  </ItemGroup>

</Project>
